// lib/constants/legazpi_barangays.dart

const List<String> kLegazpiBarangays = [
  // ── Poblacion (Urban) ──
  // ── Named Barangays ──
  'Arimbay',
  'Bagong Araw',
  'Banquerohan',
  'Bigaa',
  'Bonot',
  'Buyuan',
  'Cabangan',
  'Cagbacong',
  'Cagsawa',
  'Camaresin',
  'Capantawan',
  'Cararayan',
  'Carolina',
  'Dap-dap',
  'Dita',
  'Divina Gracia',
  'Estancia',
  'Gogon',
  'Homapon',
  'Imalnod',
  'Kawit',
  'Kilicao',
  'Kumalarang',
  'Landco',
  'Laniton',
  'Lao',
  'Larap',
  'Libod',
  'Lidong',
  'Linao',
  'Locsin',
  'Macabalo',
  'Maladong',
  'Malalbag',
  'Maligaya',
  'Maoyod',
  'Miramar',
  'Pawa',
  'Pinaric',
  'Port Area',
  'Rawis',
  'Sagumbayan',
  'San Francisco',
  'San Roque',
  'Santo Domingo',
  'Sapao',
  'Silang',
  'Situbo',
  'Tamaoyan',
  'Taysan',
  'Tinago',
  'Victory Village',
];