// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmy5Tt-MR3fwe43Vx_p4rKsaLqj-Gi1Wc',
    appId: '1:560298311855:web:cf9e9e16b249b19588d45a',
    messagingSenderId: '560298311855',
    projectId: 'homegrown-app-b71d1',
    authDomain: 'homegrown-app-b71d1.firebaseapp.com',
    storageBucket: 'homegrown-app-b71d1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbuLjfy3T3G0h6aNac11VR6jxerO8rE8w',
    appId: '1:560298311855:android:02fc72485bf61c0488d45a',
    messagingSenderId: '560298311855',
    projectId: 'homegrown-app-b71d1',
    storageBucket: 'homegrown-app-b71d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKAg_uqUs4M1f4C-tDw-On0CeapK5n1Ok',
    appId: '1:560298311855:ios:d7daa27a3b90214188d45a',
    messagingSenderId: '560298311855',
    projectId: 'homegrown-app-b71d1',
    storageBucket: 'homegrown-app-b71d1.firebasestorage.app',
    iosBundleId: 'com.homegrown.homegrown',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKAg_uqUs4M1f4C-tDw-On0CeapK5n1Ok',
    appId: '1:560298311855:ios:d7daa27a3b90214188d45a',
    messagingSenderId: '560298311855',
    projectId: 'homegrown-app-b71d1',
    storageBucket: 'homegrown-app-b71d1.firebasestorage.app',
    iosBundleId: 'com.homegrown.homegrown',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmy5Tt-MR3fwe43Vx_p4rKsaLqj-Gi1Wc',
    appId: '1:560298311855:web:bbd37354b5ec46a188d45a',
    messagingSenderId: '560298311855',
    projectId: 'homegrown-app-b71d1',
    authDomain: 'homegrown-app-b71d1.firebaseapp.com',
    storageBucket: 'homegrown-app-b71d1.firebasestorage.app',
  );
}
